



vaga0:
 link: "/vaga-598.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------


vaga1:
 link: "/vaga-333.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/08/Kelloggs-Logo.png"
 data_inicio: "31/03/2020**"
 data_fim: "31/12/2021**"
 empresa: "Nestlé"
 titulo: "kellog"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio**"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga2:
 link: "/vaga-294.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/08/Kelloggs-Logo.png"
 data_inicio: "31/03/2020**"
 data_fim: "31/12/2021**"
 empresa: "Nestlé"
 titulo: "Gerdau"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio**"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga3:
 link: "/vaga-128.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/08/Kelloggs-Logo.png"
 data_inicio: "31/03/2020**"
 data_fim: "31/12/2021**"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio TESTE"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio**"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga4:
 link: "/aga-403.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/08/Kelloggs-Logo.png"
 data_inicio: "31/03/2020**"
 data_fim: "31/12/2021**"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio TESTE"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio**"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga5:
 link: "/vaga-733.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/08/Kelloggs-Logo.png"
 data_inicio: "31/03/2020**"
 data_fim: "31/12/2021**"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio TESTE"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 descricao_curta: "Programa de estágio**"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

