



vaga0:
 link: "/vaga-598.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------


vaga1:
 link: "/vaga-333.html"
 logo: "https://media-exp1.licdn.com/dms/image/C560BAQEAxZNN_DbjsQ/company-logo_200_200/0?e=2159024400&v=beta&t=b81hHiXUwwZ_QH3GwYKJ7wjwo_o3u4MBBrmvY4ztpBE"
 data_inicio: "Vagas abertas"
 data_fim: "-"
 empresa: "Furukawa Eletric"
 titulo: "Trainee Furukawa 2020"
 site: "https://www.atsglobe.com/hotsite/traineefurukawa2020"
 tipo: "Trainee"
 descricao_curta: "Programa Trainee Furukawa"
 descricao_completa:
  "
O Programa de Trainee Furukawa 2020 busca rejuvenescer a empresa, atraindo jovens profissionais de alto potencial com foco no desenvolvimento humano e social.

Os Trainees passarão por uma imersão completa na nossa cultura por 12 meses, em uma jornada por todas as áreas da empresa realizando projetos desafiadores e relevantes.

Saiba mais: https://www.youtube.com/watch?v=_PdYiBdj6Qk

Inscreva-se no nosso programa e fique atento(a) às fases e convocações.

Boa sorte!
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga2:
 link: "/vaga-294.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/04/PG-Logo-500x280.png"
 data_inicio: "Vagas abertas"
 data_fim: "-"
 empresa: "Procter & gamble"
 titulo: "P&G - Programa de Estágio"
 site: "https://www.pgcareers.com/job/salvador/management-internship-in-sales-salvador-e-belo-horizonte/936/14742120?src=JB-15138&utm_source=site&utm_medium=CT"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
 Do you want to be in the driving seat, selling our global leading brands? Are you intrigued by the idea of building long-term business relationships with our customers? To develop and negotiate plans which create a benefit for our shoppers, our customers and our Company? Then an Internship in our Strategic Sales department is the right place for you. We are here to help you gain a magical experience. We have internship assignments in the areas of Key account management, Shopper Based Design, Category management & Business Analysis.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga3:
 link: "/vaga-128.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga4:
 link: "/vaga-403.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

vaga5:
 link: "/vaga-733.html"
 logo: "https://1000logos.net/wp-content/uploads/2017/10/Logo-Nestle-png.jpg"
 data_inicio: "31/03/2020"
 data_fim: "31/12/2021"
 empresa: "Nestlé"
 titulo: "Nestlé - Programa de Estágio"
 site: "https://www.atsglobe.com/hotsite/estagionestle"
 tipo: "Estágio"
 descricao_curta: "Programa de estágio"
 descricao_completa:
  "
  Nestlé - Programa de Estágio
Você sabia que o Programa de Estágio na Nestlé é contínuo?

E o que isso quer dizer? Quer dizer que o nosso Programa funciona durante o ano todo, ou seja:

Você permanece ativo em nosso banco, até que tenha pelo menos 1 ano para concluir o seu curso;

A gente pode entrar em contato com você a qualquer momento, para diferentes formatos de avaliação;

Uma vez que você é entrevistado, sua avaliação fica em nosso sistema e podemos entrar em contato para diferentes vagas (claro, a gente faz essa escolha juntxs, tá?)
Tem uma coisa super importante, viu? As vagas são para trabalhar em São Paulo e para início imediato.

Quer um mundo de possibilidades pra você inovar e descobrir o que mais gosta de fazer? Então vem com a gente.
  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------




